openapi: 3.0.0
info:
  version: '1.0'
  title: "is2-24"
  description: Polls is a simple API allowing consumers to view polls and vote in them.
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
  server:
    url: http://localhost:3000/
    description: localhost
paths:
  /register:
  
  /login:
  
  /home:
  
  /vetrina:
  
  /aggiungi:
  
  /logout:
  
components:
  schemas:
    user:
      type: object
      required:
        -username
        -password
      properties:
        username:
          type: string
          description: valid username
        password: 
          type: string
          description: user pwd
    shoe:
      type: object
      required:
        -brand
        -model
      properties:
        brand:
          type: string
          description: brand of the shoe
        model:
          type: string
          description: model of the shoe brand